name: Daily Quant Run

on:
  workflow_dispatch:
  schedule:
    - cron: '43 9 * * 1-5'
      timezone: 'Asia/Shanghai'
    - cron: '33 11 * * 1-5'
      timezone: 'Asia/Shanghai'
    - cron: '3 15 * * 1-5'
      timezone: 'Asia/Shanghai'
  # schedule:
  #   - cron: '43 1 * * 1-5'   # 北京时间 09:43 启动
  #   - cron: '33 3 * * 1-5'   # 北京时间 11:33 启动
  #   - cron: '3 7 * * 1-5'    # 北京时间 15:03 启动

jobs:
  run-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: quant
          environment-file: environment.yml
          auto-activate-base: false

      - name: Run quant script
        shell: bash -l {0}
        env:
          TUSHARE_TOKEN: ${{ secrets.TUSHARE_TOKEN }}
        run: |
          python main.py